# Generated by Django 5.2.5 on 2025-09-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'Can view a book'), ('can_create', 'Can create a book'), ('can_edit', 'Can edit a book'), ('can_delete', 'Can delete a book'))},
        ),
    ]
